import { Destination, Deal } from "@/lib/types";

export const mockDestinations: Destination[] = [
  {
    id: "dest-001",
    city: "Dubai",
    country: "UAE",
    image: "/dubai.png",
    startingPrice: 15800,
    currency: "INR",
    description: "Where the future meets the desert",
    tags: ["Luxury", "Shopping", "Architecture"],
    trending: true,
    spanLarge: true,
  },
  {
    id: "dest-002",
    city: "Paris",
    country: "France",
    image: "/paris.png",
    startingPrice: 48000,
    currency: "INR",
    description: "City of light, love and haute couture",
    tags: ["Romance", "Culture", "Fashion"],
    trending: false,
    spanLarge: false,
  },
  {
    id: "dest-003",
    city: "Maldives",
    country: "Maldives",
    image: "/maldives.png",
    startingPrice: 65000,
    currency: "INR",
    description: "Paradise above the Indian Ocean",
    tags: ["Overwater", "Beaches", "Diving"],
    trending: true,
    spanLarge: false,
  },
  {
    id: "dest-004",
    city: "Bali",
    country: "Indonesia",
    image: "/bali.png",
    startingPrice: 22000,
    currency: "INR",
    description: "Island of gods and golden rice fields",
    tags: ["Culture", "Wellness", "Nature"],
    trending: false,
    spanLarge: false,
  },
  {
    id: "dest-005",
    city: "London",
    country: "UK",
    image: "/london.png",
    startingPrice: 51000,
    currency: "INR",
    description: "Where heritage meets modern grandeur",
    tags: ["History", "Culture", "Shopping"],
    trending: false,
    spanLarge: true,
  },
  {
    id: "dest-006",
    city: "Singapore",
    country: "Singapore",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    startingPrice: 21500,
    currency: "INR",
    description: "The city that never stops innovating",
    tags: ["Modern", "Food", "Architecture"],
    trending: true,
    spanLarge: false,
  },
];

export const mockDeals: Deal[] = [
  {
    id: "deal-001",
    type: "flight",
    category: "cheapest",
    title: "Mumbai → Dubai",
    destination: "Dubai",
    image: "/dubai.png",
    originalPrice: 22000,
    discountedPrice: 15800,
    discount: 28,
    currency: "INR",
    validUntil: "2026-06-25",
    airline: "Emirates",
  },
  {
    id: "deal-002",
    type: "flight",
    category: "cheapest",
    title: "Delhi → Bangkok",
    destination: "Bangkok",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=400&q=80",
    originalPrice: 18500,
    discountedPrice: 11200,
    discount: 39,
    currency: "INR",
    validUntil: "2026-06-22",
    airline: "IndiGo",
  },
  {
    id: "deal-003",
    type: "flight",
    category: "weekend",
    title: "Mumbai → Goa",
    destination: "Goa",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=400&q=80",
    originalPrice: 6500,
    discountedPrice: 3200,
    discount: 51,
    currency: "INR",
    validUntil: "2026-06-21",
    airline: "Air India",
  },
  {
    id: "deal-004",
    type: "flight",
    category: "weekend",
    title: "Delhi → Shimla",
    destination: "Shimla",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=400&q=80",
    originalPrice: 4800,
    discountedPrice: 2100,
    discount: 56,
    currency: "INR",
    validUntil: "2026-06-20",
    airline: "SpiceJet",
  },
  {
    id: "deal-005",
    type: "flight",
    category: "international",
    title: "Mumbai → Paris",
    destination: "Paris",
    image: "/paris.png",
    originalPrice: 65000,
    discountedPrice: 48000,
    discount: 26,
    currency: "INR",
    validUntil: "2026-07-01",
    airline: "Qatar Airways",
  },
  {
    id: "deal-006",
    type: "hotel",
    category: "luxury",
    title: "Maldives Overwater Villa",
    destination: "Maldives",
    image: "/maldives.png",
    originalPrice: 120000,
    discountedPrice: 75000,
    discount: 37,
    currency: "INR",
    validUntil: "2026-07-15",
  },
  {
    id: "deal-007",
    type: "flight",
    category: "international",
    title: "Bangalore → Singapore",
    destination: "Singapore",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400&q=80",
    originalPrice: 28000,
    discountedPrice: 19500,
    discount: 30,
    currency: "INR",
    validUntil: "2026-06-30",
    airline: "Singapore Airlines",
  },
  {
    id: "deal-008",
    type: "hotel",
    category: "luxury",
    title: "Bali Jungle Resort",
    destination: "Bali",
    image: "/bali.png",
    originalPrice: 35000,
    discountedPrice: 22000,
    discount: 37,
    currency: "INR",
    validUntil: "2026-07-10",
  },
];
