import { Flight } from "@/lib/types";

export const mockFlights: Flight[] = [
  {
    id: "fl-101",
    airline: { code: "GF", name: "Gulf Air", logo: "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=64&q=80&fit=crop" }, // Placeholder logo for real feel
    flightNumber: "GF 133",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "04:55", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "06:55+1", terminal: "T4" },
    duration: "30h 30m",
    stops: 1,
    stopCities: ["BAH"],
    price: 271,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 5,
    baggage: { cabin: "7 kg", checked: "23 kg" },
    amenities: ["Meal", "Entertainment"],
    refundable: false,
  },
  {
    id: "fl-102",
    airline: { code: "GF", name: "Gulf Air", logo: "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=64&q=80&fit=crop" },
    flightNumber: "GF 135",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "21:50", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "06:55+1", terminal: "T4" },
    duration: "13h 35m",
    stops: 1,
    stopCities: ["BAH"],
    price: 272,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 2,
    baggage: { cabin: "7 kg", checked: "23 kg" },
    amenities: ["Meal", "Entertainment"],
    refundable: false,
  },
  {
    id: "fl-103",
    airline: { code: "GF", name: "Gulf Air", logo: "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=64&q=80&fit=crop" },
    flightNumber: "GF 137",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "04:55", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "15:20", terminal: "T4" },
    duration: "14h 55m",
    stops: 1,
    stopCities: ["BAH"],
    price: 272,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 8,
    baggage: { cabin: "7 kg", checked: "23 kg" },
    amenities: ["Meal", "Entertainment"],
    refundable: false,
  },
  {
    id: "fl-104",
    airline: { code: "6E", name: "IndiGo", logo: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=64&q=80&fit=crop" },
    flightNumber: "6E 11",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "10:50", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "17:45", terminal: "T2" },
    duration: "11h 25m",
    stops: 0,
    price: 274,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 12,
    baggage: { cabin: "7 kg", checked: "0 kg" },
    amenities: ["Meal for purchase"],
    refundable: false,
  },
  {
    id: "fl-105",
    airline: { code: "VS", name: "Virgin Atlantic", logo: "https://images.unsplash.com/photo-1517400508447-f8dd518b86db?w=64&q=80&fit=crop" },
    flightNumber: "VS 301",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "11:10", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "16:15", terminal: "T3" },
    duration: "9h 35m",
    stops: 0,
    price: 321,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 4,
    baggage: { cabin: "10 kg", checked: "23 kg" },
    amenities: ["WiFi", "Meal", "Entertainment", "USB"],
    refundable: true,
  },
  {
    id: "fl-106",
    airline: { code: "VS", name: "Virgin Atlantic", logo: "https://images.unsplash.com/photo-1517400508447-f8dd518b86db?w=64&q=80&fit=crop" },
    flightNumber: "VS 303",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "02:05", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "07:20", terminal: "T3" },
    duration: "9h 45m",
    stops: 0,
    price: 322,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 9,
    baggage: { cabin: "10 kg", checked: "23 kg" },
    amenities: ["WiFi", "Meal", "Entertainment", "USB"],
    refundable: true,
  },
  {
    id: "fl-107",
    airline: { code: "QR", name: "Qatar Airways", logo: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=64&q=80&fit=crop" },
    flightNumber: "QR 579",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "03:25", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "18:00", terminal: "T4" },
    duration: "19h 05m",
    stops: 1,
    stopCities: ["DOH"],
    price: 324,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 6,
    baggage: { cabin: "7 kg", checked: "25 kg" },
    amenities: ["WiFi", "Premium Meal", "Entertainment"],
    refundable: true,
  },
  {
    id: "fl-108",
    airline: { code: "QR", name: "Qatar Airways", logo: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=64&q=80&fit=crop" },
    flightNumber: "QR 581",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "21:30", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "08:00+1", terminal: "T4" },
    duration: "15h 00m",
    stops: 1,
    stopCities: ["DOH"],
    price: 325,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 3,
    baggage: { cabin: "7 kg", checked: "25 kg" },
    amenities: ["WiFi", "Premium Meal", "Entertainment"],
    refundable: true,
  },
  {
    id: "fl-109",
    airline: { code: "AI", name: "Air India", logo: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=64&q=80&fit=crop" },
    flightNumber: "AI 111",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "09:30", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "19:30", terminal: "T2" },
    duration: "14h 30m",
    stops: 1,
    stopCities: ["BOM"],
    price: 359,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 14,
    baggage: { cabin: "8 kg", checked: "25 kg" },
    amenities: ["Meal", "Entertainment"],
    refundable: true,
  },
  {
    id: "fl-110",
    airline: { code: "SV", name: "Saudia", logo: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=64&q=80&fit=crop" },
    flightNumber: "SV 759",
    departure: { airport: { code: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India" }, time: "11:25", terminal: "T3" },
    arrival: { airport: { code: "LHR", name: "Heathrow", city: "London", country: "UK" }, time: "20:30", terminal: "T4" },
    duration: "13h 35m",
    stops: 1,
    stopCities: ["JED"],
    price: 363,
    currency: "USD",
    cabin: "economy",
    seatsLeft: 7,
    baggage: { cabin: "7 kg", checked: "23 kg" },
    amenities: ["Meal", "Entertainment"],
    refundable: true,
  }
];

export const airlines = ["Gulf Air", "IndiGo", "Virgin Atlantic", "Qatar Airways", "Air India", "Saudia"];
