import { Hotel } from "@/lib/types";

export const mockHotels: Hotel[] = [
  {
    id: "ht-001",
    name: "Burj Al Arab Jumeirah",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    location: "Jumeirah Beach Road",
    city: "Dubai",
    country: "UAE",
    rating: 4.9,
    reviewCount: 3842,
    pricePerNight: 45000,
    currency: "INR",
    stars: 5,
    amenities: ["Private Beach", "Infinity Pool", "Spa", "Fine Dining", "Helipad", "Butler Service"],
    tags: ["Iconic", "Ultra Luxury", "Beachfront"],
    featured: true,
  },
  {
    id: "ht-002",
    name: "Four Seasons George V",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    location: "31 Avenue George V",
    city: "Paris",
    country: "France",
    rating: 4.8,
    reviewCount: 2198,
    pricePerNight: 68000,
    currency: "INR",
    stars: 5,
    amenities: ["Michelin Restaurant", "Spa", "Concierge", "Bar", "Pool", "Valet"],
    tags: ["Historic", "Luxury", "City Center"],
    featured: true,
  },
  {
    id: "ht-003",
    name: "The Ritz-Carlton Maldives",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    location: "Fari Islands, North Malé Atoll",
    city: "Maldives",
    country: "Maldives",
    rating: 4.9,
    reviewCount: 1204,
    pricePerNight: 92000,
    currency: "INR",
    stars: 5,
    amenities: ["Private Villa", "Coral Reef", "Overwater Spa", "Water Sports", "Fine Dining", "Yacht"],
    tags: ["Overwater", "Romantic", "All-Inclusive"],
    featured: true,
  },
  {
    id: "ht-004",
    name: "Marina Bay Sands",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    location: "10 Bayfront Avenue",
    city: "Singapore",
    country: "Singapore",
    rating: 4.7,
    reviewCount: 8921,
    pricePerNight: 28000,
    currency: "INR",
    stars: 5,
    amenities: ["Infinity Pool", "Casino", "Skypark", "Spa", "Shopping Mall", "Celebrity Restaurants"],
    tags: ["Iconic", "City Views", "Rooftop Pool"],
    featured: false,
  },
  {
    id: "ht-005",
    name: "COMO Uma Ubud",
    image: "https://images.unsplash.com/photo-1535827841776-24afc1e255ac?w=800&q=80",
    location: "Jalan Raya Sanggingan",
    city: "Bali",
    country: "Indonesia",
    rating: 4.8,
    reviewCount: 967,
    pricePerNight: 24500,
    currency: "INR",
    stars: 5,
    amenities: ["Private Pool Villa", "Rainforest Views", "Yoga", "Spa", "Organic Restaurant", "Trekking"],
    tags: ["Jungle", "Wellness", "Romantic"],
    featured: false,
  },
  {
    id: "ht-006",
    name: "The Savoy London",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
    location: "Strand, Covent Garden",
    city: "London",
    country: "UK",
    rating: 4.7,
    reviewCount: 5431,
    pricePerNight: 55000,
    currency: "INR",
    stars: 5,
    amenities: ["Thames Views", "Gordon Ramsay Restaurant", "Spa", "Pool", "Afternoon Tea", "Concierge"],
    tags: ["Historic", "Central London", "Fine Dining"],
    featured: false,
  },
];
