import { Hotel } from "@/lib/types";

export const mockHotels: Hotel[] = [
  {
    id: "ht-001",
    name: "Burj Al Arab Jumeirah",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80"
    ],
    location: "Jumeirah Beach Road",
    address: "Jumeirah Street, Umm Suqeim 3, Dubai",
    city: "Dubai",
    country: "UAE",
    rating: 4.9,
    reviewCount: 3842,
    pricePerNight: 45000,
    currency: "INR",
    stars: 5,
    amenities: ["Private Beach", "Infinity Pool", "Spa", "Fine Dining", "Helipad", "Butler Service", "Free WiFi"],
    tags: ["Iconic", "Ultra Luxury", "Beachfront"],
    featured: true,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "The world's most luxurious hotel featuring duplex suites with private butler service, underwater dining, and stunning Arabian Gulf views.",
    rooms: [
      {
        roomId: "rm-101",
        roomType: "Deluxe One-Bedroom Suite",
        boardBasis: "Breakfast Included",
        pricePerNight: 45000,
        totalPrice: 45000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 48 hours before check-in",
        available: true,
      },
      {
        roomId: "rm-102",
        roomType: "Panoramic Ocean Suite",
        boardBasis: "Half Board (Breakfast + Dinner)",
        pricePerNight: 58000,
        totalPrice: 58000,
        currency: "INR",
        maxOccupancy: 3,
        cancellationPolicy: "Non-refundable",
        available: true,
      }
    ]
  },
  {
    id: "ht-002",
    name: "Four Seasons George V",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    location: "31 Avenue George V",
    address: "31 Avenue George V, 75008 Paris",
    city: "Paris",
    country: "France",
    rating: 4.8,
    reviewCount: 2198,
    pricePerNight: 68000,
    currency: "INR",
    stars: 5,
    amenities: ["Michelin Restaurant", "Spa", "Concierge", "Bar", "Pool", "Valet", "Free WiFi"],
    tags: ["Historic", "Luxury", "City Center"],
    featured: true,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "An art-deco landmark built in 1928, located just off the Champs-Élysées, offering three Michelin-starred dining options.",
    rooms: [
      {
        roomId: "rm-201",
        roomType: "Superior Room with Courtyard View",
        boardBasis: "Breakfast Included",
        pricePerNight: 68000,
        totalPrice: 68000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-003",
    name: "The Ritz-Carlton Maldives",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    location: "Fari Islands, North Malé Atoll",
    address: "Fari Islands, North Malé Atoll 20013",
    city: "Maldives",
    country: "Maldives",
    rating: 4.9,
    reviewCount: 1204,
    pricePerNight: 92000,
    currency: "INR",
    stars: 5,
    amenities: ["Private Villa", "Coral Reef", "Overwater Spa", "Water Sports", "Fine Dining", "Yacht"],
    tags: ["Overwater", "Romantic", "All-Inclusive"],
    featured: true,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "Architectural masterpiece over the Indian Ocean with private infinity pools, Aris Meeha personal hosts, and world-class diving.",
    rooms: [
      {
        roomId: "rm-301",
        roomType: "Ocean Overwater Pool Villa",
        boardBasis: "All-Inclusive",
        pricePerNight: 92000,
        totalPrice: 92000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation up to 7 days before arrival",
        available: true,
      }
    ]
  },
  {
    id: "ht-004",
    name: "Marina Bay Sands",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    location: "10 Bayfront Avenue",
    address: "10 Bayfront Avenue, Singapore 018956",
    city: "Singapore",
    country: "Singapore",
    rating: 4.7,
    reviewCount: 8921,
    pricePerNight: 28000,
    currency: "INR",
    stars: 5,
    amenities: ["Infinity Pool", "Casino", "Skypark", "Spa", "Shopping Mall", "Celebrity Restaurants"],
    tags: ["Iconic", "City Views", "Rooftop Pool"],
    featured: false,
    checkInTime: "15:00",
    checkOutTime: "11:00",
    description: "Home to the world's largest rooftop infinity pool, offering sweeping skyline views of Singapore's financial district.",
    rooms: [
      {
        roomId: "rm-401",
        roomType: "Deluxe King City View",
        boardBasis: "Room Only",
        pricePerNight: 28000,
        totalPrice: 28000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 48 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-005",
    name: "COMO Uma Ubud",
    image: "https://images.unsplash.com/photo-1535827841776-24afc1e255ac?w=800&q=80",
    location: "Jalan Raya Sanggingan",
    address: "Jl. Raya Sanggingan, Kedewatan, Ubud, Bali",
    city: "Bali",
    country: "Indonesia",
    rating: 4.8,
    reviewCount: 967,
    pricePerNight: 24500,
    currency: "INR",
    stars: 5,
    amenities: ["Private Pool Villa", "Rainforest Views", "Yoga", "Spa", "Organic Restaurant", "Trekking"],
    tags: ["Jungle", "Wellness", "Romantic"],
    featured: false,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "Luxury resort nestled in the Tjampuhan Valley, offering holistic wellness programs and serene jungle views.",
    rooms: [
      {
        roomId: "rm-501",
        roomType: "Ubud Suite with Valley View",
        boardBasis: "Breakfast Included",
        pricePerNight: 24500,
        totalPrice: 24500,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-006",
    name: "The Savoy London",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
    location: "Strand, Covent Garden",
    address: "Strand, London WC2R 0EZ, UK",
    city: "London",
    country: "UK",
    rating: 4.7,
    reviewCount: 5431,
    pricePerNight: 55000,
    currency: "INR",
    stars: 5,
    amenities: ["Thames Views", "Gordon Ramsay Restaurant", "Spa", "Pool", "Afternoon Tea", "Concierge"],
    tags: ["Historic", "Central London", "Fine Dining"],
    featured: false,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "Britain's premier historic hotel on the banks of the Thames, where luxury meets glamour in the heart of London.",
    rooms: [
      {
        roomId: "rm-601",
        roomType: "Luxury King River View",
        boardBasis: "Breakfast Included",
        pricePerNight: 55000,
        totalPrice: 55000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-007",
    name: "Atlantis The Royal",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    location: "Crescent Road, Palm Jumeirah",
    address: "Crescent Rd - Palm Jumeirah - Dubai - UAE",
    city: "Dubai",
    country: "UAE",
    rating: 4.9,
    reviewCount: 1850,
    pricePerNight: 62000,
    currency: "INR",
    stars: 5,
    amenities: ["Rooftop Skypool", "Private Beach", "Aquaventure Waterpark", "Nobu Restaurant", "Spa", "Free WiFi"],
    tags: ["New Landmark", "Ultra Luxury", "Palm Jumeirah"],
    featured: true,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "Dubai's newest ultra-luxury architectural icon on the Palm Jumeirah, home to Cloud 22 skypool and Michelin-starred dining.",
    rooms: [
      {
        roomId: "rm-701",
        roomType: "Seascape King Room",
        boardBasis: "Breakfast Included",
        pricePerNight: 62000,
        totalPrice: 62000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 48 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-008",
    name: "Armani Hotel Dubai",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    location: "Burj Khalifa, Downtown Dubai",
    address: "Burj Khalifa - Boulevard - Downtown Dubai - UAE",
    city: "Dubai",
    country: "UAE",
    rating: 4.8,
    reviewCount: 2410,
    pricePerNight: 39000,
    currency: "INR",
    stars: 5,
    amenities: ["Burj Khalifa Access", "Armani Spa", "Fine Dining", "Concierge", "Valet", "Free WiFi"],
    tags: ["High Style", "Downtown", "Burj Khalifa"],
    featured: false,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "Nestled inside the iconic Burj Khalifa, designed personally by Giorgio Armani with signature understated elegance.",
    rooms: [
      {
        roomId: "rm-801",
        roomType: "Armani Deluxe Room",
        boardBasis: "Breakfast Included",
        pricePerNight: 39000,
        totalPrice: 39000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-009",
    name: "Jumeirah Zabeel Saray",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    location: "West Crescent, Palm Jumeirah",
    address: "The Palm Jumeirah - Crescent West - Dubai - UAE",
    city: "Dubai",
    country: "UAE",
    rating: 4.8,
    reviewCount: 3100,
    pricePerNight: 32000,
    currency: "INR",
    stars: 5,
    amenities: ["Talise Ottoman Spa", "Private Cinema", "Infinity Pool", "Private Beach", "Free WiFi"],
    tags: ["Ottoman Palace", "Beachfront", "Spa Sanctuary"],
    featured: false,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "Ottoman-inspired palace resort offering opulent marble interiors, hand-painted murals, and one of the Middle East's largest spas.",
    rooms: [
      {
        roomId: "rm-901",
        roomType: "Superior King Ocean View",
        boardBasis: "Breakfast Included",
        pricePerNight: 32000,
        totalPrice: 32000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-010",
    name: "The Taj Mahal Palace",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    location: "Apollo Bunder, Colaba",
    address: "Apollo Bunder, Colaba, Mumbai, Maharashtra 400001",
    city: "Mumbai",
    country: "India",
    rating: 4.9,
    reviewCount: 12450,
    pricePerNight: 26000,
    currency: "INR",
    stars: 5,
    amenities: ["Arabian Sea Views", "Jiva Spa", "Historic Butler Service", "Wasabi Restaurant", "Free WiFi"],
    tags: ["Heritage Landmark", "Sea View", "Historic"],
    featured: true,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "India's iconic heritage luxury hotel built in 1903, overlooking the Gateway of India and Arabian Sea.",
    rooms: [
      {
        roomId: "rm-1001",
        roomType: "Palace Wing Luxury Sea View Room",
        boardBasis: "Breakfast Included",
        pricePerNight: 26000,
        totalPrice: 26000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-011",
    name: "JW Marriott Marquis Hotel Dubai",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80",
    location: "Sheikh Zayed Road, Business Bay",
    address: "Sheikh Zayed Rd - Business Bay - Dubai - UAE",
    city: "Dubai",
    country: "UAE",
    rating: 4.8,
    reviewCount: 5120,
    pricePerNight: 28500,
    currency: "INR",
    stars: 5,
    amenities: ["Free WiFi", "Saray Spa", "14 Restaurants & Bars", "Outdoor Pool", "Valet Parking"],
    tags: ["Business Luxury", "Business Bay", "Iconic Towers"],
    featured: true,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "The world's tallest 5-star hotel towers, offering spectacular views of Dubai Canal, luxury dining, and world-class spa facilities.",
    rooms: [
      {
        roomId: "rm-1101",
        roomType: "Deluxe Corner Suite with Canal View",
        boardBasis: "Breakfast Included",
        pricePerNight: 28500,
        totalPrice: 28500,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-012",
    name: "Holiday Inn Express Dubai",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    location: "Internet City",
    address: "Dubai Internet City - Dubai - UAE",
    city: "Dubai",
    country: "UAE",
    rating: 4.2,
    reviewCount: 1840,
    pricePerNight: 7500,
    currency: "INR",
    stars: 3,
    amenities: ["Free Express Breakfast", "Free WiFi", "Fitness Center", "Free Parking"],
    tags: ["Budget Friendly", "Internet City", "Convenient"],
    featured: false,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "Modern & affordable hotel located in the heart of Dubai Internet City, ideal for tech & business travelers.",
    rooms: [
      {
        roomId: "rm-1201",
        roomType: "Standard Queen Room",
        boardBasis: "Free Express Breakfast",
        pricePerNight: 7500,
        totalPrice: 7500,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-013",
    name: "Novotel World Trade Centre",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    location: "World Trade Centre",
    address: "Al Mustaqbal St - Trade Centre - Trade Centre 2 - Dubai - UAE",
    city: "Dubai",
    country: "UAE",
    rating: 4.4,
    reviewCount: 2900,
    pricePerNight: 13500,
    currency: "INR",
    stars: 4,
    amenities: ["Free WiFi", "Outdoor Swimming Pool", "Jazz Bar", "Shuttle to Beach"],
    tags: ["Convention Center", "Trade Centre", "Family Friendly"],
    featured: false,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "Connected to the Dubai International Convention and Exhibition Centre, featuring international dining and outdoor pool.",
    rooms: [
      {
        roomId: "rm-1301",
        roomType: "Superior Room with City View",
        boardBasis: "Breakfast Included",
        pricePerNight: 13500,
        totalPrice: 13500,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-014",
    name: "Wildflower Hall, An Oberoi Resort",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    location: "Chharabra, Shimla",
    address: "Chharabra, Shimla, Himachal Pradesh 171012",
    city: "Shimla",
    country: "India",
    rating: 4.9,
    reviewCount: 1540,
    pricePerNight: 28000,
    currency: "INR",
    stars: 5,
    amenities: ["Heated Outdoor Jacuzzi", "Mountain Views", "Spa", "Fine Dining", "Free WiFi"],
    tags: ["Himalayan Luxury", "Heritage", "Spa Resort"],
    featured: true,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "Former residence of Lord Kitchener nestled 8,250 feet above sea level amidst pine forests with outdoor heated infinity spa.",
    rooms: [
      {
        roomId: "rm-1401",
        roomType: "Premier Mountain View Room",
        boardBasis: "Breakfast Included",
        pricePerNight: 28000,
        totalPrice: 28000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 48 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-015",
    name: "Taj Exotica Resort & Spa",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    location: "Benaulim Beach, South Goa",
    address: "Benaulim, Salcete, Goa 403716",
    city: "Goa",
    country: "India",
    rating: 4.8,
    reviewCount: 4120,
    pricePerNight: 22000,
    currency: "INR",
    stars: 5,
    amenities: ["Private Beach", "Golf Course", "Jiva Spa", "Outdoor Pool", "Free WiFi"],
    tags: ["Beachfront Luxury", "South Goa", "Resort"],
    featured: true,
    checkInTime: "15:00",
    checkOutTime: "12:00",
    description: "Mediterranean-inspired luxury resort set in 56 acres of lush gardens along the pristine Benaulim beach.",
    rooms: [
      {
        roomId: "rm-1501",
        roomType: "Premium Garden View Villa",
        boardBasis: "Breakfast Included",
        pricePerNight: 22000,
        totalPrice: 22000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-016",
    name: "The Leela Palace New Delhi",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    location: "Chanakyapuri, Diplomatic Enclave",
    address: "Diplomatic Enclave, Chanakyapuri, New Delhi 110023",
    city: "New Delhi",
    country: "India",
    rating: 4.9,
    reviewCount: 5890,
    pricePerNight: 24000,
    currency: "INR",
    stars: 5,
    amenities: ["Rooftop Heated Pool", "Megu & Jamavar Restaurants", "ESPA Spa", "Butler Service", "Free WiFi"],
    tags: ["Royal Architecture", "Diplomatic Enclave", "Ultra Luxury"],
    featured: true,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "Grand palace hotel blending Lutyens architectural grandeur with royal Indian hospitality and Michelin-starred dining.",
    rooms: [
      {
        roomId: "rm-1601",
        roomType: "Grand Deluxe Room",
        boardBasis: "Breakfast Included",
        pricePerNight: 24000,
        totalPrice: 24000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 24 hours before check-in",
        available: true,
      }
    ]
  },
  {
    id: "ht-017",
    name: "The Oberoi Udaivilas",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    location: "Haridasji Ki Magri, Lake Pichola",
    address: "Badi-Gorela-Mulltal Rd, Haridas Ji Ki Magri, Udaipur, Rajasthan 313001",
    city: "Udaipur",
    country: "India",
    rating: 4.9,
    reviewCount: 3200,
    pricePerNight: 38000,
    currency: "INR",
    stars: 5,
    amenities: ["Semi-Private Pool", "Lake Pichola Boat Arrival", "Palace Courtyards", "Spa", "Free WiFi"],
    tags: ["Palace Resort", "Lake View", "Royal Rajasthan"],
    featured: true,
    checkInTime: "14:00",
    checkOutTime: "12:00",
    description: "Sprawling 30-acre royal palace resort on the banks of Lake Pichola with domes, corridors, and boat transfers.",
    rooms: [
      {
        roomId: "rm-1701",
        roomType: "Premier Room with Semi-Private Pool",
        boardBasis: "Breakfast Included",
        pricePerNight: 38000,
        totalPrice: 38000,
        currency: "INR",
        maxOccupancy: 2,
        cancellationPolicy: "Free cancellation until 48 hours before check-in",
        available: true,
      }
    ]
  }
];
