import { SightseeingTour } from "../types";

export const mockSightseeingTours: SightseeingTour[] = [
  {
    id: "tour-001",
    title: "Dubai Premium Red Dune Desert Safari with 4x4 Dune Bashing & VIP BBQ",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1000&q=80",
    city: "Dubai",
    country: "UAE",
    durationHours: 6,
    rating: 4.9,
    reviewCount: 1840,
    pricePerPerson: 4500,
    originalPrice: 6500,
    currency: "INR",
    category: "safari",
    featured: true,
    inclusions: [
      "Hotel Pickup & Dropoff by 4x4",
      "Red Dune Bashing & Sandboarding",
      "Camel Riding & Henna Painting",
      "VIP Buffet BBQ Dinner",
      "Tanoura & Belly Dance Shows",
    ],
    description:
      "Experience the ultimate Arabian desert adventure. Includes thrilling 4x4 dune bashing across Lahbab red dunes, sunset photo ops, camel rides, and a VIP dinner at a traditional Bedouin camp.",
  },
  {
    id: "tour-002",
    title: "Universal Studios Singapore VIP 1-Day Express Pass",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1000&q=80",
    city: "Singapore",
    country: "Singapore",
    durationHours: 8,
    rating: 4.8,
    reviewCount: 1250,
    pricePerPerson: 7200,
    originalPrice: 9000,
    currency: "INR",
    category: "theme_park",
    featured: true,
    inclusions: [
      "1-Day Unlimited Express Pass",
      "Fast-track queue skip for all rides",
      "S$20 Dining & Shopping Voucher",
      "Sentosa Express Island Monorail Ticket",
    ],
    description:
      "Skip the lines and immerse yourself in movie magic at Universal Studios Singapore. Enjoy VIP priority access to Transformers, Battlestar Galactica, and Jurassic Park.",
  },
  {
    id: "tour-003",
    title: "Paris Eiffel Tower Priority Access & Seine River Dinner Cruise",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1000&q=80",
    city: "Paris",
    country: "France",
    durationHours: 5,
    rating: 4.9,
    reviewCount: 980,
    pricePerPerson: 12500,
    originalPrice: 15000,
    currency: "INR",
    category: "cruise",
    featured: true,
    inclusions: [
      "Eiffel Tower 2nd Floor Skip-The-Line Access",
      "3-Course Gourmet French Dinner on Glass-Top Boat",
      "Live Violinist Performance",
      "Champagne Toast",
    ],
    description:
      "Experience Paris in all its romantic glory. Fast-track your entrance to the Eiffel Tower followed by a glass-canopied dinner cruise along the Seine River.",
  },
  {
    id: "tour-004",
    title: "Goa Grand Island Scuba Diving & Speedboat Dolphin Safari",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1000&q=80",
    city: "Goa",
    country: "India",
    durationHours: 7,
    rating: 4.7,
    reviewCount: 890,
    pricePerPerson: 3800,
    originalPrice: 5200,
    currency: "INR",
    category: "water_sports",
    inclusions: [
      "Speedboat ride to Grand Island",
      "Scuba Diving with PADI Instructor & Underwater Photos/Video",
      "Dolphin Sightseeing",
      "Goan Buffet Lunch & Beers",
    ],
    description:
      "Dive into crystal waters off Grand Island in Goa. Includes underwater photo session, PADI instructor guidance, dolphin watching, and beachfront buffet lunch.",
  },
  {
    id: "tour-005",
    title: "Maldives Sunset Catamaran Cruise & Snorkeling with Sea Turtles",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1000&q=80",
    city: "Male",
    country: "Maldives",
    durationHours: 4,
    rating: 4.95,
    reviewCount: 640,
    pricePerPerson: 8900,
    originalPrice: 11000,
    currency: "INR",
    category: "cruise",
    inclusions: [
      "Luxury Catamaran Sailing",
      "Turtle Reef Snorkeling Gear & Guide",
      "Tropical Fruit Platter & Mocktails",
      "Underwater GoPro Photos",
    ],
    description:
      "Sail aboard a luxury catamaran through pristine Maldivian lagoons. Swim alongside wild sea turtles and enjoy sunset mocktails.",
  },
];
