import { TransferOption } from "../types";

export const mockTransferOptions: TransferOption[] = [
  {
    id: "tr-001",
    vehicleName: "Mercedes-Benz S-Class Luxury Chauffeur",
    vehicleType: "luxury_limo",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=1000&q=80",
    capacityPassengers: 3,
    baggageCount: 3,
    pickupLocation: "Dubai International Airport (DXB)",
    dropoffLocation: "Burj Al Arab / Downtown Dubai",
    price: 6800,
    currency: "INR",
    vehicleClass: "First Class Chauffeur",
    featured: true,
    features: [
      "Flight Tracking & 60-min Free Airport Wait",
      "Executive Chauffeur in Suit",
      "In-car WiFi, Refreshments & Leather Seats",
      "Meet & Greet at Arrivals Hall",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before pickup",
  },
  {
    id: "tr-002",
    vehicleName: "Cadillac Escalade VIP SUV Transfer",
    vehicleType: "suv",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1000&q=80",
    capacityPassengers: 6,
    baggageCount: 6,
    pickupLocation: "Mumbai Airport (BOM) / Delhi (DEL)",
    dropoffLocation: "5-Star Hotel City Transfers",
    price: 8500,
    currency: "INR",
    vehicleClass: "VIP Large Luxury SUV",
    featured: true,
    features: [
      "Spacious Leather Seating for 6",
      "6 Large Suitcase Capacity",
      "60-min Flight Delay Protection",
      "Complimentary Bottled Water & Mints",
    ],
    cancellationPolicy: "Free cancellation up to 12 hours before pickup",
  },
  {
    id: "tr-003",
    vehicleName: "BMW 7-Series Executive Sedan",
    vehicleType: "sedan",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1000&q=80",
    capacityPassengers: 3,
    baggageCount: 2,
    pickupLocation: "Paris CDG / London LHR",
    dropoffLocation: "City Center Hotels",
    price: 7400,
    currency: "INR",
    vehicleClass: "Business Executive Class",
    features: [
      "Professional Multilingual Driver",
      "Privacy Tinted Glass & Ambient Lighting",
      "All Tolls & Parking Included",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before pickup",
  },
  {
    id: "tr-004",
    vehicleName: "Mercedes-Benz V-Class VIP Passenger Van",
    vehicleType: "minivan",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1000&q=80",
    capacityPassengers: 7,
    baggageCount: 8,
    pickupLocation: "Singapore Changi / Goa Airport",
    dropoffLocation: "Resort Transfers",
    price: 5900,
    currency: "INR",
    vehicleClass: "Luxury Group Van",
    features: [
      "Conference Seating Arrangement",
      "Extra Luggage Capacity",
      "Family & Group Friendly",
    ],
    cancellationPolicy: "Free cancellation up to 24 hours before pickup",
  },
];
