import { Villa } from "../types";

export const mockVillas: Villa[] = [
  {
    id: "villa-001",
    name: "The Baga Beachfront Luxury Villa",
    location: "Baga Beach, North Goa",
    city: "Goa",
    country: "India",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1000&q=80",
    pricePerNight: 28000,
    bedrooms: 4,
    maxGuests: 10,
    rating: 4.9,
    reviewCount: 320,
    featured: true,
    amenities: ["Private Pool", "Direct Beach Access", "Butler Service", "Jacuzzi", "Free WiFi", "BBQ Grill"],
  },
  {
    id: "villa-002",
    name: "Coorg Coffee Estate Heritage Homestay",
    location: "Madikeri, Coorg",
    city: "Coorg",
    country: "India",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1000&q=80",
    pricePerNight: 14500,
    bedrooms: 3,
    maxGuests: 8,
    rating: 4.8,
    reviewCount: 210,
    featured: true,
    amenities: ["Estate Walks", "Home-cooked South Indian Food", "Fireplace", "Mountain View", "Pet Friendly"],
  },
  {
    id: "villa-003",
    name: "Manali Alpine Snow Chalet & Spa",
    location: "Old Manali, Himachal Pradesh",
    city: "Manali",
    country: "India",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1000&q=80",
    pricePerNight: 22000,
    bedrooms: 5,
    maxGuests: 12,
    rating: 4.95,
    reviewCount: 180,
    featured: true,
    amenities: ["Heated Wooden Rooms", "Snow Mountain Views", "Sauna & Hot Tub", "Chef on Request"],
  },
];
